# Generated by Django 5.2.6 on 2025-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('socks', 'Socks'), ('shoes', 'Shoes'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
